version: "2"


services:
    # pg:
    #     image: postgres:13
        # expose:
        #     - ${POSTGRES_PORT}
        # ports:
        #     - ${POSTGRES_PORT}:${POSTGRES_PORT}
        # command: -p ${POSTGRES_PORT}
    #     environment:
    #         - POSTGRES_DB=${POSTGRES_DB}
    #         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #         - POSTGRES_USER=${POSTGRES_USER}
    #     volumes:
    #         - pg_data_startup:/var/lib/postgresql/data
    bot:
        build: .
        # depends_on:
        #     - pg
        env_file: .env


# volumes:
#     anubis_mirror_bot_postgres:
#         external: true